# Issu de la dernière image OpenJDK 11
FROM adoptopenjdk/openjdk11:x86_64-alpine-jdk-11.0.6_10-slim
MAINTAINER vincent.zwingmann@gmail.com

# Copy de l'archive
COPY service-comptes.jar /opt/service-comptes.jar

# Lancement de l'appli
CMD java -jar /opt/service-comptes.jar