# Issu de la dernière image OpenJDK 11
FROM openjdk:11-jdk-stretch
MAINTAINER vincent.zwingmann@gmail.com

# Copy de l'archive
COPY service-comptes.jar /opt/service-comptes.jar

# Lancement de l'appli
CMD java -jar /opt/service-comptes.jar