package com.terrier.finances.gestion.ui.components.auth;

import com.terrier.finances.gestion.ui.components.abstrait.AbstractUIComponent;
import com.terrier.finances.gestion.ui.controler.auth.LoginController;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.v7.ui.Label;
import com.vaadin.v7.ui.PasswordField;
import com.vaadin.v7.ui.TextField;
import com.vaadin.v7.ui.VerticalLayout;

import elemental.events.KeyboardEvent.KeyCode;

/**
 * Page de login
 * @author vzwingma
 *
 */
public class Login extends AbstractUIComponent<LoginController> {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private GridLayout mainLayout;
	@AutoGenerated
	private VerticalLayout VersionLayout;
	@AutoGenerated
	private Label labelBuildTime;
	@AutoGenerated
	private Label labelVersion;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private VerticalLayout AuthlLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Button buttonConnexion;
	@AutoGenerated
	private PasswordField passwordField;
	@AutoGenerated
	private TextField textLogin;
	@AutoGenerated
	private Label label_1;
	/**
	 * 
	 */
	private static final long serialVersionUID = -8912123300643969099L;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Login() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		// Start
		startControleur();
	}


	/**
	 * @return the buttonConnexion
	 */
	public Button getButtonConnexion() {
		return buttonConnexion;
	}

	/**
	 * @return the passwordField
	 */
	public PasswordField getPasswordField() {
		return passwordField;
	}

	/**
	 * @return the textLogin
	 */
	public TextField getTextLogin() {
		return textLogin;
	}

	/* (non-Javadoc)
	 * @see com.terrier.finances.gestion.ui.components.AbstractUIComponent#getControleur()
	 */
	@Override
	public LoginController createControleur() {
		return new LoginController(this);
	}

	/**
	 * @return the labelBuildTime
	 */
	public Label getLabelBuildTime() {
		return labelBuildTime;
	}

	/**
	 * @return the labelVersion
	 */
	public Label getLabelVersion() {
		return labelVersion;
	}

	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setStyleName("fondbleu");
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		mainLayout.setColumns(3);
		mainLayout.setRows(3);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// AuthlLayout
		AuthlLayout = buildAuthlLayout();
		mainLayout.addComponent(AuthlLayout, 1, 1);
		mainLayout.setComponentAlignment(AuthlLayout, new Alignment(48));

		// verticalLayout_2
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setWidth("150px");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(false);
		mainLayout.addComponent(verticalLayout_2, 0, 2);
		mainLayout.setComponentAlignment(verticalLayout_2, new Alignment(9));

		// VersionLayout
		VersionLayout = buildVersionLayout();
		mainLayout.addComponent(VersionLayout, 2, 2);
		mainLayout.setComponentAlignment(VersionLayout, new Alignment(10));

		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildAuthlLayout() {
		// common part: create layout
		AuthlLayout = new VerticalLayout();
		AuthlLayout.setStyleName("loginLayout");
		AuthlLayout.setWidth("-1px");
		AuthlLayout.setHeight("-1px");
		AuthlLayout.setMargin(false);
		AuthlLayout.setSpacing(true);

		// label_1
		label_1 = new Label();
		label_1.setStyleName("login-header");
		label_1.setImmediate(false);
		label_1.setWidth("200px");
		label_1.setHeight("-1px");
		label_1.setValue("  Authentification");
		AuthlLayout.addComponent(label_1);
		AuthlLayout.setComponentAlignment(label_1, new Alignment(48));

		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		AuthlLayout.addComponent(verticalLayout_1);
		AuthlLayout.setComponentAlignment(verticalLayout_1, new Alignment(48));

		return AuthlLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setWidth("-1px");
		verticalLayout_1.setHeight("200px");
		verticalLayout_1.setMargin(false);

		// textLogin
		textLogin = new TextField();
		textLogin.setCaption("Login");
		textLogin.setImmediate(true);
		textLogin.setDescription("Entrer le login");
		textLogin.setWidth("100.0%");
		textLogin.setHeight("-1px");
		textLogin.setId("login");
		verticalLayout_1.addComponent(textLogin);

		// passwordField
		passwordField = new PasswordField();
		passwordField.setCaption("Mot de passe");
		passwordField.setImmediate(true);
		passwordField.setDescription("Entrer le mot de passe");
		passwordField.setWidth("100.0%");
		passwordField.setHeight("-1px");
		passwordField.setId("password");
		verticalLayout_1.addComponent(passwordField);

		// buttonConnexion
		buttonConnexion = new Button();
		buttonConnexion.setClickShortcut(KeyCode.ENTER);
		buttonConnexion.setStyleName("primary");
		buttonConnexion.setCaption("Connexion");
		buttonConnexion.setWidth("145px");
		buttonConnexion.setHeight("-1px");
		verticalLayout_1.addComponent(buttonConnexion);
		verticalLayout_1.setComponentAlignment(buttonConnexion, new Alignment(
				48));

		return verticalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildVersionLayout() {
		// common part: create layout
		VersionLayout = new VerticalLayout();
		VersionLayout.setWidth("150px");
		VersionLayout.setHeight("-1px");
		VersionLayout.setMargin(false);

		// labelVersion
		labelVersion = new Label();
		labelVersion.setStyleName("versionLabel");
		labelVersion.setImmediate(false);
		labelVersion.setWidth("-1px");
		labelVersion.setHeight("-1px");
		labelVersion.setValue("Version : ");
		VersionLayout.addComponent(labelVersion);

		// labelBuildTime
		labelBuildTime = new Label();
		labelBuildTime.setStyleName("versionLabel");
		labelBuildTime.setImmediate(false);
		labelBuildTime.setWidth("-1px");
		labelBuildTime.setHeight("-1px");
		labelBuildTime.setValue("Build : ");
		VersionLayout.addComponent(labelBuildTime);

		return VersionLayout;
	}


}
