# Issu de la dernière image OpenJDK 11
FROM openjdk:11.0.14.1-jre-slim-buster
MAINTAINER vincent.zwingmann@gmail.com

# Copy de l'archive
COPY service-utilisateurs.jar /opt/service-utilisateurs.jar

# Lancement de l'appli
CMD java -jar /opt/service-utilisateurs.jar -Djdk.tls.client.protocols=TLSv1.2