# Issu de la dernière image OpenJDK 8
FROM openjdk:8-alpine
MAINTAINER vincent.zwingmann@gmail.com

# Copy de l'archive
COPY service-parametrages.jar /opt/service-parametrages.jar

# Lancement de l'appli
CMD java -jar /opt/service-parametrages.jar