# Issu de la dernière image OpenJDK 11
FROM openjdk:11-jdk-stretch
MAINTAINER vincent.zwingmann@gmail.com

# Copy de l'archive
COPY service-budgets.jar /opt/service-budgets.jar

# Lancement de l'appli
CMD java -jar /opt/service-budgets.jar