# Issu de l'image en cours
FROM gordonff/rpi-tomcat
MAINTAINER vincent.zwingmann@gmail.com

# Copy de l'archive
COPY services.war /usr/local/tomcat/webapps/services.war

# Droit pour tous les users de Tomcat
RUN chmod a+r -R /usr/local/tomcat; \
    chmod 777 -R /usr/local/tomcat;